# Generated by Django 3.2.18 on 2023-02-23 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ModelPunch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('punch_in', models.BooleanField(default=False)),
                ('punch_in_time', models.DateTimeField(blank=True, null=True)),
                ('punch_out', models.BooleanField(default=False)),
                ('punch_out_time', models.DateTimeField(blank=True, null=True)),
                ('hours_for_day', models.DecimalField(blank=True, decimal_places=2, default='0.00', max_digits=4, null=True)),
            ],
            options={
                'ordering': ['date'],
            },
        ),
    ]
