# Generated by Django 3.2.18 on 2023-02-23 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('punchin_out_api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeDitels',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee', models.CharField(max_length=100)),
            ],
        ),
    ]
