# Generated by Django 3.2.18 on 2023-02-23 09:29

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('punchin_out_api', '0002_employeeditels'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='modelpunch',
            options={},
        ),
        migrations.RemoveField(
            model_name='modelpunch',
            name='date',
        ),
        migrations.RemoveField(
            model_name='modelpunch',
            name='punch_in',
        ),
        migrations.RemoveField(
            model_name='modelpunch',
            name='punch_in_time',
        ),
        migrations.AddField(
            model_name='employeeditels',
            name='date',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='employeeditels',
            name='punch_in',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='employeeditels',
            name='punch_in_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
