# Generated by Django 3.2.18 on 2023-02-23 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('punchin_out_api', '0003_auto_20230223_1459'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employeeditels',
            name='employee',
        ),
        migrations.AlterField(
            model_name='employeeditels',
            name='punch_in',
            field=models.BooleanField(default=True),
        ),
    ]
