# Generated by Django 3.2.18 on 2023-02-23 10:17

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('punchin_out_api', '0005_auto_20230223_1528'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeeditels',
            name='date',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='employeeditels',
            name='hours_for_day',
            field=models.DecimalField(blank=True, decimal_places=2, default='0.00', max_digits=4, null=True),
        ),
        migrations.AddField(
            model_name='employeeditels',
            name='punch_in',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='employeeditels',
            name='punch_in_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='employeeditels',
            name='punch_out',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='employeeditels',
            name='punch_out_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
