# Generated by Django 3.2.18 on 2023-02-23 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('punchin_out_api', '0007_auto_20230223_1551'),
    ]

    operations = [
        migrations.AddField(
            model_name='modelpunch',
            name='ids',
            field=models.IntegerField(default=0),
        ),
    ]
