# Generated by Django 3.2.18 on 2023-02-23 11:35

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('punchin_out_api', '0008_modelpunch_ids'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ModelPunch',
        ),
        migrations.AddField(
            model_name='employeeditels',
            name='name',
            field=models.CharField(default=django.utils.timezone.now, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='employeeditels',
            name='punch_out',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='employeeditels',
            name='punch_out_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
